### ISSUE TITLE
Immediate crash on any command using the example bot

### ISSUE THREAD

**Issue by peppizza** [MikeModder/anpan#10]
```
Example bot for anpan.
Version 1.2.0.
Initializing...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x6bc003]

goroutine 20 [running]:
github.com/MikeModder/anpan.(*CommandHandler).MessageHandler(0xc00012a230, 0xc00007e480, 0xc0004e2030)
        C:/Users/Spencer/go/pkg/mod/github.com/!mike!modder/anpan@v0.0.0-20200727120832-8f9b09f45257/handler.go:404 +0x513
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc000030e00, 0xc00007e480, 0x70dba0, 0xc0004e2030)
        C:/Users/Spencer/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x5e
created by github.com/bwmarrin/discordgo.(*Session).handle
        C:/Users/Spencer/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118
```

**Comment by yeah-its-gloria** [comment]
The new release, `v7.1.4`, fixes this issue.
